apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab
  template:
    metadata:
      labels:
        app: lab
    spec:
      containers:
        - name: lab
          image: rodrigodiez/pub-in:${CIRCLE_SHA1}
          ports:
            - containerPort: 8080
          env:
            - name: NGINX_PORT
              value: "8080"
