apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub-in-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pub-in-web
  template:
    metadata:
      labels:
        app: pub-in-web
        app.kubernetes.io/name: pub-in-web
        app.kubernetes.io/instance: pub-in-web
        app.kubernetes.io/version: "${CIRCLE_SHA1}"
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: pub-in
    spec:
      containers:
        - name: nginx
          image: rodrigodiez/pub-in:${CIRCLE_SHA1}
          ports:
            - containerPort: 8080
          env:
            - name: NGINX_PORT
              value: "8080"
