apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pub-in-web
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - pub-in.lab.rodrigodiez.io
      secretName: pub-in-tls
  rules:
    - host: pub-in.lab.rodrigodiez.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: pub-in-web
              servicePort: 80
          - path: /api
            pathType: Prefix
            backend:
              serviceName: pub-in-svc
              servicePort: 80
